### ISSUE TITLE
Update test names to include expected outcome

### ISSUE THREAD

**Issue by jaredroach** [NCATSTranslator/Tests#27]
The "test results" spreadsheet is currently of little utility for troubleshooting because a SMRF cannot know what the expected outcome of the the test is. The only way to do that appears to dig into the json repository here. Which is error prone if done by human eyes. And greatly slows down manual evaluation. Can we add a column to the "Test Results" that says what the desired outcome of the test is (e.g., "Hexadrin should never show up in results for the query 'What drugs_may_treat_Premature_Menopause?'")? Might be a pretty quick script to parse the json files to create that column...

**Comment by maximusunc** [comment]
Hi Jared, thanks for the feedback! I think the correct fix here is to update the test names themselves to be more descriptive. Right now they're all just "X_treats_Y", but we should update to "X_should_never_treat_Y". I'll also point out that the "Test Results" spreadsheet is geared more towards ARAs finding their failing tests in an easier manner at this early stage in automated testing and is not meant to stick around long term. If you open up the same test in the Information Radiator, you'll be able to see the test input, which includes the desired outcome of the test.

**Comment by jaredroach** [comment]
OK. My use case is immediately downstream from "ARAs finding their failing tests in an easier manner". Now that we have found it, we want to think about what to do next. As a first step in automating, we want to explore some of these to understand what sort of algorithmic fixes should be added. So I am indeed asking for something more than the spreadsheet was originally designed for, but it seems like a reasonable request. 

Maybe the information radiator has all this information in an easier-to-access manner? Can someone provide a link to the information radiator? I have not yet used it.

**Comment by maximusunc** [comment]
I added a new sheet that has a url for each row that will take you directly to that test in the Information Radiator: https://docs.google.com/spreadsheets/d/1x1BvzuU5EDmovvkaVAT6yG7-HC7lkgK8hELMqwoHNNQ/edit#gid=602065052

**Comment by jaredroach** [comment]
Thanks. Is there a dictionary somewhere that explains the code for each possible "expected_output"? For example, what does 'TopAnswer' mean? Must be #1? Must be above a certain score? Must be in top 10? Must be in top 10 after resolving equivalences (such as steroids or NSAIDs)? something else?

**Comment by maximusunc** [comment]
We currently have an issue open for that (https://github.com/NCATSTranslator/Tests/issues/13) but the current ruling is this:
1_TopAnswer: The expected output is in the top 10% of results
2_Acceptable: The expected output is in the top 50% of results
3_BadButForgivable: The expected output is either not present or in the bottom 50% of results
4_NeverShow: The expected output is not in the results

**Comment by maximusunc** [comment]
Expected outcome has been added to test names
