### ISSUE TITLE
TestCase_21: castleman disease, not multiple sclerosis? Do tests/assets need double-checking?

### ISSUE THREAD

**Issue by colleenXu** [NCATSTranslator/Tests#34]
For [TestCase_21](https://github.com/NCATSTranslator/Tests/blob/9a18068831c8702d5f5a341bd26f11d956b887a2/test_cases/TestCase_21.json#L15), the input disease name seems off. The disease ID is recorded as "multiple sclerosis", but the ID actually seems to be for Castleman disease ([NodeNorm link](https://nodenorm.ci.transltr.io/1.4/get_normalized_nodes?curie=MONDO%3A0015564)). 

VS [TestCase_8](https://github.com/NCATSTranslator/Tests/blob/main/test_cases/TestCase_8.json) is for multiple sclerosis and its ID seems to match ([NodeNorm link](https://nodenorm.ci.transltr.io/1.4/get_normalized_nodes?curie=MONDO%3A0005301))

**Comment by maximusunc** [comment]
Should have closed this with my last comment.
