### ISSUE TITLE
Problem with ADRB2 "decreases" tests

### ISSUE THREAD

**Issue by colleenXu** [NCATSTranslator/Tests#37]
I notice that there are tests for both "increases activity or abundance" of ADRB2 and "decreases activity or abundance" of ADRB2 (In the [spreadsheet](https://docs.google.com/spreadsheets/d/1x1BvzuU5EDmovvkaVAT6yG7-HC7lkgK8hELMqwoHNNQ/edit?usp=sharing), this is testCase_20: assets 307-308, 378-389.)

However, ALL of the tests use the same "increases" query and response. This can be seen by looking at the Test Runner links. Example: this ["decreases" test](https://informationradiator.renci.org/test-runs/53/tests/9160)'s logs show that an "increases" query was actually run. This also can be seen when looking at the PKs in ARAX-UI - the individual tool's query-graphs show that an "increases" query was sent to them. 

So the "decreases" tests aren't being applied to "decreases" queries and responses.

**Comment by maximusunc** [comment]
@sierra-moxon it looks like there's an error in the test generation script that is grouping both decreased and increased MVP2 test assets together.
