### ISSUE TITLE
Ensure all asset output ids are filled in

### ISSUE THREAD

**Issue by maximusunc** [NCATSTranslator/Tests#4]
If a test curator only provides an output name, I think we should send it through the Name Resolver on ingestion to the Tests repo. The Runners will need the output id and I don't think we should obtain it at run-time.

**Comment by RichardBruskiewich** [comment]
Hi @maximusunc, the most robust solution (@sierra-moxon correct me if I'm wrong) would be to annotate the **TestAsset** model slot for **`output_id`** as **`required: true`**.

Following this line of reasoning, it is tempting to ask what are _**all**_ of the required slots of a **TestAsset**?  I would personally hazard to guess that the following list of **TestAsset** slots are such:

- **`id`** - required by inheritance from the **TestEntity** parent class
- **`input_id`**
- **`predicate`**
- **`output_id`**
- **`expected_output`**

All the other fields of the TestAsset model are likely optional (again, @jh111, @sierra-moxon correct me if I'm wrong).

I will issue a PR to add **`required: true`** to all of the above slots which lack the directive.

**Comment by RichardBruskiewich** [comment]
Potentially enforced by PR https://github.com/TranslatorSRI/TranslatorTestingModel/pull/15.

**Comment by maximusunc** [comment]
One caveat I'd like to point out here. It's my understanding that the Data Harmonizer spreadsheet that Sierra created uses the model, so that would require these fields to be filled in, but I'm worried that a non-technical user might not know how to fill out the input and output ids (not to mention that it kind of needs to use the preferred curie from node normalizer). My opinion is that the best way to do this is to keep the Data Harmonizer a little less strict and then inside our Asset -> Test Case script, we name resolve and node normalize all the ids that are missing.

**Comment by jh111** [comment]
I agree we want non-technical people to be able to add assets. However, from a testing perspective, I think it will be best to have those cases fail. Test failures may be bugs in the product or bugs in the test. Have nice red failures will motivate SMuRFs like me to get my IDs done, and help SMEs who can't do it.

**Comment by maximusunc** [comment]
Are you saying the IDs should not be required, but the test should fail until one is provided?

**Comment by jh111** [comment]
Yes, I think that would be ideal longer term. If TAQA says a test is important, than it's a priority to get both the test and Translator working.

**Comment by RichardBruskiewich** [comment]
I said "Node Normalizer" above but I'm wondering if it's keyword searching on concept annotation.

As you mention to me on Slack, maybe such queries against the **my-*-info** resources?
