### ISSUE TITLE
Remove TestAsset 16

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Tests#43]
Test Asset 16 states that CHEBI:50453 treats Aceruloplasminemia.  I think this is wrong - that CHEBI identifier is for a superclass of the chemical that is the active ingredient.  That answer is already given as asset 305.

**Comment by jh111** [comment]
Yes - it can be removed, thank you.
@maximusunc @ShervinAbd92 Should the "Asset:16" row be deleted, reused or marked as retired?

**Comment by maximusunc** [comment]
I think it should just be removed. I'll go ahead and do that now.
