### ISSUE TITLE
Asset_16: remove?

### ISSUE THREAD

**Issue by colleenXu** [NCATSTranslator/Tests#50]
[Asset_16](https://github.com/NCATSTranslator/Tests/blob/main/test_assets/Asset_16.json) uses `CHEBI:50453` for desferrioxamine, which doesn't have any synonymous IDs ([NodeNorm CI link](https://nodenorm.ci.transltr.io/1.4/get_normalized_nodes?curie=CHEBI%3A50453&conflate=true&drug_chemical_conflate=true&description=false)). 

EDIT: However, [Asset_305](https://github.com/NCATSTranslator/Tests/blob/main/test_assets/Asset_305.json) is for [Deferoxamine](https://en.wikipedia.org/wiki/Deferoxamine), another name for this drug. It seems to have more synonymous IDs and seems to be what ARAs are using (BTE, Aragorn, Unsecret). 
* PUBCHEM.COMPOUND:2973 is the current primary ID for [NodeNorm CI](https://nodenorm.ci.transltr.io/1.4/get_normalized_nodes?curie=CHEBI%3A4356&conflate=true&drug_chemical_conflate=true&description=false)
* CHEBI:4356 is the current primary ID for [NodeNorm Dev](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=CHEBI%3A4356&conflate=true&drug_chemical_conflate=true&description=false)

Perhaps Asset_16 can be deleted in favor of Asset_305?

**Comment by sierra-moxon** [comment]
@jh111 - asset_16 is one you added; what do you think of Colleen's suggestion?

**Comment by maximusunc** [comment]
Duplicate of #43. Removed.
