### ISSUE TITLE
Better/as good results/assets?

### ISSUE THREAD

**Issue by dkoslicki** [NCATSTranslator/Tests#65]
Test 9 asset 618, has CHEBI:7772 omeprazole as a target top answer, [ARAX returns](https://arax.ncats.io/?r=2e5b71e2-3a80-4848-95af-44394ff99e74) esomeprazole CHEBI:50275 which seems like it should also count as correct

**Comment by maximusunc** [comment]
I'm a little confused by the results in the ARAX GUI. The first result header says omeprazole, but shows the curie for esomeprazole, but then result 3 is listed as esomeprazole with the same curie?

**Comment by dkoslicki** [comment]
Yeah, that is odd (and likely our bug; I'm seeing that Omeprazole is correctly referenced in the edge bindings, but the node bindings swapped out that for Esomeprazole). But I was more indicating that both omeprazole and esomeprazole seem like equally good answers.

**Comment by maximusunc** [comment]
I would say that in the case that they're both equally good answers, you can add esomeprazole as an additional test asset. But it sounds like there isn't a question of whether or not Omeprazole is a good test asset to have. The test assets are finite, but we're always willing to add more for a more complete test bed.

**Comment by dkoslicki** [comment]
Yup, sounds good! It's still head-scratching that no ARA got Omeprazole... will be interesting to see the various reasons as teams address these (us included)

**Comment by dkoslicki** [comment]
Since it's marked as closed, did we/you want to add esomeprazole, or not at this point?

**Comment by maximusunc** [comment]
Opened a new issue: #70
