### ISSUE TITLE
Incorrect CURIE/synonymization?

### ISSUE THREAD

**Issue by dkoslicki** [NCATSTranslator/Tests#66]
Test 11 asset 386, the goal is salmeterol (PUBCHEM.COMPOUND:5582) and [ARAX returns](https://arax.ncats.io/?r=0fb3c248-d026-4505-8aa1-028d02837012) Salmeterol (CHEBI:64064) as result 7 of 77 (~9%) but is counted as failing.

**Comment by maximusunc** [comment]
PR opened: https://github.com/NCATSTranslator/Tests/pull/68

**Comment by maximusunc** [comment]
Fixed.

**Comment by colleenXu** [comment]
Adding a note! I agree with the update to [CHEBI:64064](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=CHEBI:64064&conflate=true&drug_chemical_conflate=true&description=false)

The old answer ID `PUBCHEM.COMPOUND:5582` appears to be something else with a long name ([Dev NodeNorm](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=PUBCHEM.COMPOUND:5582&conflate=true&drug_chemical_conflate=true&description=false), [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/5582))
