### ISSUE TITLE
Asset 367: wrong answer ID for Bupropion

### ISSUE THREAD

**Issue by colleenXu** [NCATSTranslator/Tests#77]
This asset currently uses `PUBCHEM.COMPOUND:3031065` as the expected answer ID for Bupropion. But this chemical appears to have a different structure than Bupropion ([the chlorine on its ring](https://pubchem.ncbi.nlm.nih.gov/compound/3031065#section=Structures) is in a diff position compared to [Bupropion](https://pubchem.ncbi.nlm.nih.gov/compound/444#section=Structures)). I also think the NodeNorm entry for this ID seems odd: none of the ID labels are bupropion ([Dev NodeNorm](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=PUBCHEM.COMPOUND:3031065&conflate=true&drug_chemical_conflate=true&description=false)). 

Instead, there's another entity with the name Bupropion and lots of equivalent IDs, including the [PUBCHEM.COMPOUND:444](https://pubchem.ncbi.nlm.nih.gov/compound/444) that I referenced above: [CHEBI:3219](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=CHEBI:3219&conflate=true&drug_chemical_conflate=true&description=false). 
This shows up in BTE's results with a high score/rank (top 10%). 

I think the answer ID for this test needs to be changed.

**Comment by colleenXu** [comment]
Updated issue: figured out that the wrong ID is being used, so this isn't a synonymization issue.

**Comment by maximusunc** [comment]
Confirmed `CHEBI:3219` with Name Resolver.
