### ISSUE TITLE
Incorrect CHEBI 

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Tests#8]
Asset 16 says [CHEBI:50453](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:50453). But the proper chebi should be [CHEBI:4356](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:4356).

The one in the test is a parent grouping class that includes many subtypes but 4356 is the actual drug.

**Comment by cbizon** [comment]
@maximusunc I'm not sure how to tag Jenn here and I don't have the ability to assign the issue anyway

**Comment by cbizon** [comment]
attn: @jh111

**Comment by jh111** [comment]
Thanks - I've corrected this, and added more actual results from Translator.
- Asset 303: CHEBI:2972 | deferipone
- Asset 304: CHEBI:49005 | deferasirox
- Asset 305: PUBCHEM.COMPOUND:2973 | Deferoxamine
We have a challenge where we don't expect SME's to know CURIEs. I'll add discussing this process to the Testing agenda.
@cbizon
