### ISSUE TITLE
Asset 493: bad answer ID for pembrolizumab

### ISSUE THREAD

**Issue by colleenXu** [NCATSTranslator/Tests#82]
[Asset 493](https://github.com/NCATSTranslator/Tests/blob/main/test_assets/Asset_493.json) says the expected output name is `pembrolizumab`. However, the output ID `Substance SID: 481101797` is not a valid CURIE. 

Using [Wikipedia](https://en.wikipedia.org/wiki/Pembrolizumab), I think I found a good ID for pembrolizumab: [UNII:DPT0O3T46P](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=UNII:DPT0O3T46P&conflate=true&drug_chemical_conflate=true&description=false). 

I think the expected output ID needs to be changed.

**Comment by colleenXu** [comment]
I think all tools have been consistently failing this test, which is due to the answer ID: https://github.com/NCATSTranslator/Tests/issues/69

**Comment by maximusunc** [comment]
Confirmed with Name Resolver.
