### ISSUE TITLE
Asset 599: bad answer ID for MPO, duplicate?

### ISSUE THREAD

**Issue by colleenXu** [NCATSTranslator/Tests#88]
[Asset 599](https://github.com/NCATSTranslator/Tests/blob/main/test_assets/Asset_599.json) currently uses `CHEMBL.TARGET:CHEMBL2439` as the expected answer ID for MPO. However, `CHEMBL.TARGET:CHEMBL2439` is likely something no ARA/KP recognizes. [NodeNorm doesn't resolve this ID.](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=CHEMBL.TARGET:CHEMBL2439&conflate=true&drug_chemical_conflate=true&description=false).

Instead, I wonder about using the conflated MPO (gene)/myeloperoxidase (protein) [NCBIGene:4353](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=NCBIGene:4353&conflate=true&drug_chemical_conflate=true&description=false).

But if we changed to that ID, this would be a duplicate of [Asset 597](https://github.com/NCATSTranslator/Tests/blob/main/test_assets/Asset_597.json). Similar to https://github.com/NCATSTranslator/Tests/issues/87

Should this test be removed as a duplicate?

**Comment by colleenXu** [comment]
Noted as a test all tools fail in https://github.com/NCATSTranslator/Tests/issues/69

**Comment by maximusunc** [comment]
I agree that this should probably be removed as bad/duplicate.
